export const pdfTools = [
  // Merge & Organize
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    icon: 'merge',
    category: 'organize',
    color: 'bg-red-500',
    href: '/tools/merge-pdf',
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract pages from PDF or split into multiple files',
    icon: 'split',
    category: 'organize',
    color: 'bg-orange-500',
    href: '/tools/split-pdf',
    popular: true,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to the orientation you need',
    icon: 'rotate',
    category: 'organize',
    color: 'bg-amber-500',
    href: '/tools/rotate-pdf',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete unwanted pages from your PDF',
    icon: 'trash',
    category: 'organize',
    color: 'bg-red-600',
    href: '/tools/remove-pages',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Rearrange, delete and rotate PDF pages with ease',
    icon: 'reorder',
    category: 'organize',
    color: 'bg-rose-500',
    href: '/tools/organize-pdf',
  },

  // Optimize
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while keeping quality',
    icon: 'compress',
    category: 'optimize',
    color: 'bg-emerald-500',
    href: '/tools/compress-pdf',
    popular: true,
  },

  // Convert to PDF
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    icon: 'word',
    category: 'convert-to-pdf',
    color: 'bg-blue-600',
    href: '/tools/word-to-pdf',
    popular: true,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format',
    icon: 'excel',
    category: 'convert-to-pdf',
    color: 'bg-green-600',
    href: '/tools/excel-to-pdf',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF',
    icon: 'ppt',
    category: 'convert-to-pdf',
    color: 'bg-orange-600',
    href: '/tools/ppt-to-pdf',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert images to PDF documents',
    icon: 'image',
    category: 'convert-to-pdf',
    color: 'bg-pink-500',
    href: '/tools/jpg-to-pdf',
    popular: true,
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages to PDF documents',
    icon: 'html',
    category: 'convert-to-pdf',
    color: 'bg-cyan-500',
    href: '/tools/html-to-pdf',
  },

  // Convert from PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files to editable Word documents',
    icon: 'word',
    category: 'convert-from-pdf',
    color: 'bg-blue-600',
    href: '/tools/pdf-to-word',
    popular: true,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract data from PDF to Excel spreadsheets',
    icon: 'excel',
    category: 'convert-from-pdf',
    color: 'bg-green-600',
    href: '/tools/pdf-to-excel',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF files to editable presentations',
    icon: 'ppt',
    category: 'convert-from-pdf',
    color: 'bg-orange-600',
    href: '/tools/pdf-to-ppt',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    icon: 'image',
    category: 'convert-from-pdf',
    color: 'bg-pink-500',
    href: '/tools/pdf-to-jpg',
    popular: true,
  },

  // Edit PDF
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes to your PDF',
    icon: 'edit',
    category: 'edit',
    color: 'bg-purple-500',
    href: '/tools/edit-pdf',
  },
  {
    id: 'add-watermark',
    name: 'Watermark PDF',
    description: 'Stamp an image or text on your PDF',
    icon: 'watermark',
    category: 'edit',
    color: 'bg-indigo-500',
    href: '/tools/add-watermark',
  },
  {
    id: 'add-page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers to your PDF document',
    icon: 'numbers',
    category: 'edit',
    color: 'bg-violet-500',
    href: '/tools/add-page-numbers',
  },
  {
    id: 'redaction-pdf',
    name: 'Redact PDF',
    description: 'Redact text and graphics to permanently remove sensitive information',
    icon: 'redact',
    category: 'edit',
    color: 'bg-fuchsia-500',
    href: '/tools/redaction-pdf',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Remove margins and crop PDF pages to exact size',
    icon: 'crop',
    category: 'edit',
    color: 'bg-rose-600',
    href: '/tools/crop-pdf',
  },

  // Security
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt PDF with a password',
    icon: 'lock',
    category: 'security',
    color: 'bg-slate-700',
    href: '/tools/protect-pdf',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password from protected PDF',
    icon: 'unlock',
    category: 'security',
    color: 'bg-slate-600',
    href: '/tools/unlock-pdf',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add your signature to PDF documents',
    icon: 'signature',
    category: 'security',
    color: 'bg-slate-800',
    href: '/tools/sign-pdf',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files',
    icon: 'repair',
    category: 'security',
    color: 'bg-green-600',
    href: '/tools/repair-pdf',
  },
  {
    id: 'pdf-forms',
    name: 'PDF Forms',
    description: 'Detect and fill PDF forms automatically',
    icon: 'form',
    category: 'security',
    color: 'bg-amber-600',
    href: '/tools/pdf-forms',
  },

  // AI Tools
  {
    id: 'ai-document-assistant',
    name: 'AI Document Assistant',
    description: 'Summarize, translate, extract data, and analyze PDFs with AI',
    icon: 'sparkles',
    category: 'ai',
    color: 'bg-gradient-to-r from-purple-500 to-pink-500',
    href: '/tools/ai-document-assistant',
    premium: true,
    popular: true,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract text from scanned PDFs using OCR',
    icon: 'scan',
    category: 'ai',
    color: 'bg-blue-500',
    href: '/tools/ocr-pdf',
  },
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    description: 'Get AI-powered summary of your PDF content',
    icon: 'sparkles',
    category: 'ai',
    color: 'bg-gradient-to-r from-blue-500 to-purple-500',
    href: '/tools/ai-summarizer',
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate your PDF to different languages',
    icon: 'languages',
    category: 'ai',
    color: 'bg-teal-500',
    href: '/tools/translate-pdf',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Compare two PDF files and spot differences',
    icon: 'compare',
    category: 'ai',
    color: 'bg-cyan-500',
    href: '/tools/compare-pdf',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Convert document scans and images into PDF',
    icon: 'camera',
    category: 'ai',
    color: 'bg-lime-500',
    href: '/tools/scan-to-pdf',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to PDF/A for long-term archival',
    icon: 'archive',
    category: 'ai',
    color: 'bg-violet-600',
    href: '/tools/pdf-to-pdfa',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert PDF pages to PNG images',
    icon: 'image',
    category: 'ai',
    color: 'bg-fuchsia-600',
    href: '/tools/pdf-to-png',
  },
]

export const categories = [
  { id: 'organize', name: 'Organize PDF', icon: 'folder' },
  { id: 'optimize', name: 'Optimize', icon: 'zap' },
  { id: 'convert-to-pdf', name: 'Convert to PDF', icon: 'file-input' },
  { id: 'convert-from-pdf', name: 'Convert from PDF', icon: 'file-output' },
  { id: 'edit', name: 'Edit PDF', icon: 'edit' },
  { id: 'security', name: 'PDF Security', icon: 'shield' },
  { id: 'ai', name: 'AI Tools', icon: 'sparkles' },
]
